import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import BaseLayout from "@/components/BaseLayout";
import { useState } from "react";

export default function Login() {
  const [user, setUser] = useState({ name: "" });
  return (
    <>
      <Head>
        <title>Open Farm | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BaseLayout>
          <div className="card" style={{ width: "40rem" }}>
            <div className="card-body new">
              <h5 className="card-title">Login</h5>
              <div className="card-text-center">
                <form>
                  <p className="card-text">
                    {" "}
                    USERNAME <br />
                    <input
                      type="text"
                      onChange={(event) => {
                        setUser({ ...user, name: event.target.value });
                      }}
                      value={user.name}
                    />
                    <br />
                    <br />
                  </p>
                  <p className="card-text">
                    PASSWORD <br />
                    <input type="text" name="pass" /> <br /> <br />
                  </p>
                  <button type="button" className="btn btn-primary">
                    Button
                  </button>
                </form>
              </div>
            </div>
          </div>
        </BaseLayout>
      </main>
    </>
  );
}
