import Head from "next/head";
import Link from "next/link";
import BaseLayout from "@/components/BaseLayout";
import { useState } from "react";
import { Auth } from "@supabase/auth-ui-react";
import { ThemeSupa } from "@supabase/auth-ui-shared";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import { checkUserLoggedIn } from "../utils/auth";
import { useEffect } from "react";
import { useRouter } from "next/router";

export default function Login() {
  const session = useSession();
  const supabase = useSupabaseClient();
  const router = useRouter();

  // useEffect(() => {
  //   supabase.auth.onAuthStateChange((event, session) => {
  //     console.log(event, session);
  //   });
  // }, [session]);

  return (
    <>
      <Head>
        <title>Open Farm | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BaseLayout home>
          <div className="login justify-content-center align-items-center">
            <div
              className="bg-secondary rounded-5 p-3"
              style={{ width: "20rem" }}
            >
              <h5 className="text-center fw-bold mb-3">Login/SignUp</h5>
              <Auth
                supabaseClient={supabase}
                appearance={{ theme: ThemeSupa }}
                theme="dark"
              />
            </div>

            <div className="w-50 ms-5">
              <h1>
                {`"`}Farming is a <span className="text-primary">unique</span>{" "}
                combination of nature, economics, and culture.{`"`}
              </h1>
              <h1 className="text-primary d-flex justify-content-end align-items-center w-100">
                - Wendell Berry
              </h1>
            </div>
          </div>
        </BaseLayout>
      </main>
    </>
  );
}
