import { useState } from "react";
import Head from "next/head";
import BaseLayout from "@/components/BaseLayout";


 const post = () => {
  return (
    <Head>
    <title>Open Farm | Login</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <main> 
      <BaseLayout>
  </BaseLayout>    
  </main>
   
  )
}
export default post;
