import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import BaseLayout from "@/components/BaseLayout";
import Modal from 'react-modal'
import { useState } from "react";

export default function Post() {
    const [isOpen, setIsOpen] = useState(false);
  return( 
    <>
      <Head>
        <title>Open Farm | Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BaseLayout>
        <div className="post_body">
        <h1 className="post_header"> SELECT ROLES </h1>
         <div div className="post_select">     
         <button onClick={() => setIsOpen(true)}>Open Modal</button>
         <button onClick={() => setIsOpen(true)}>Open Modal</button>
         <button onClick={() => setIsOpen(true)}>Open Modal</button>
         <button onClick={() => setIsOpen(true)}>Open Modal</button>
         <button onClick={() => setIsOpen(true)}>Open Modal</button>
         </div>
         <Modal isOpen={isOpen} onRequestClose={() => setIsOpen(false)} >
            <h1>Modal Content</h1>
            <button onClick={() => setIsOpen(false)}>Close Modal</button>
         </Modal>
      </div>
        </BaseLayout>
      </main>
    </>
  );
}
