import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import BaseLayout from "@/components/BaseLayout";
import { useState } from "react";

export default function Register() {
  const [user, setUser] = useState({ name: "" });
  const [phone,setPhone] = useState({phoneno:""});
  const [email,setEmail] = useState({emailid:""});
  const [pass,setPass] = useState({passwrd:""});
  const [confirm,setConfirm] = useState({confirmation:""});
  
  return (
    <>
      <Head>
        <title>Open Farm | Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BaseLayout>
        <div className="login">     
          <div className="card">
            <div className="card-body new">
              <h3 className="card-title">REGISTERS</h3>
              <div className="card-text-center">
                <form>
                  <p className="card-text">
                    USERNAME <br />
                    <input
                      type="text"
                      className="input_field"
                      onChange={(event) => {
                        setUser({ ...user, name: event.target.value });
                      }}
                      value={user.name}
                    />
                    <br />
                    <br />
                  </p>
                  <p className="card-text">
                    PHONE NUMBER <br />
                    <input
                      className="input_field"
                      type="text"
                      name="pass"
                      onChange={(event) => {
                        setPhone({ ...phone, phone: event.target.value });
                      }}
                      value={user.name}
                    />{" "}
                    <br /> <br />
                  </p>
                  <p className="card-text">
                    EMAIL <br />
                    <input
                      type="email"
                      className="input_field"
                      onChange={(event) => {
                        setEmail({ ...email, emailid: event.target.value });
                      }}
                      value={email.emailid}
                    />
                    <br />
                    <br />
                  </p>
                  <p className="card-text">
                    CREATE PASSWORD <br />
                    <input
                      type="password"
                      className="input_field"
                      onChange={(event) => {
                        setPass({ ...pass, passwrd: event.target.value });
                      }}
                      value={pass.passwrd}
                    />
                    <br />
                    <br />
                  </p>
                  <p className="card-text">
                    CONFIRM PASSWORD <br />
                    <input
                      type="passwords"
                      className="input_field"
                      onChange={(event) => {
                        setConfirmation({ ...confirm, confirmation: event.target.value });
                      }}
                      value={confirm.confirmation}
                    />
                    <br />
                    <br />
                  </p>
                  <button type="button" className="btn btn-primary_login">
                    Register
                  </button>
                  <br /> <br />
                </form>
              </div>
            </div>
          </div>
          < div className="right_content">     
          <h1>
              {`"`}A <span> quote </span> that fits{`"`}
            </h1>
          </div>
          </div>
       
        </BaseLayout>
      </main>
    </>
  );
}
     
