import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import BaseLayout from "@/components/BaseLayout";
import { useState } from "react";

export default function Register() {
  const [user, setUser] = useState({ name: "" });
  return (
    <>
      <Head>
        <title>Open Farm | Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BaseLayout>
       
        </BaseLayout>
      </main>
    </>
  );
}
     
